project:
  type: website

website:
  title: "Stata2r"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: data_table.qmd
        text: "Data wrangling with `data.table`"
      - href: fixest.qmd
        text: "Regression analysis with `fixest`"
      - href: extras.qmd
        text: "Other great packages"

execute:
  cache: true

format:
  html:
    theme: 
      - cosmo
      - partials/cell-output.scss
      - partials/split-code.scss
    highlight-style: github
    toc: true
    toc-location: left
    toc-depth: 2
    toc-expand: 4
    include-after-body: 
      - partials/toggle-output.html # Button to toggle code visibility


